#make BOLDdistilled lib persist.

name: bip

services:
  bip:
    image: ghcr.io/cbg-innov/bip:latest
    pull_policy: missing
    working_dir: /BIP
    volumes:
      - reflib:/BIP/REFS
      - ${BIP_DATA:-./data}:/data
    command: ["sleep", "infinity"]
volumes:
  reflib: